mpc_parameters:
  mpc_N: 10
  nx: 13
  nu: 12
  speed_limx: 2.0
  fz_max: 1000.0
  g: 9.8
  miu: 0.4
  d_time: 0.01

control_gains:
  Kpp: [25.0, 25.0, 120.0]
  Kdp: [25.0, 25.0, 25.0]
  kpw: 500.0
  Kdw: [60.0, 60.0, 60.0]
  KpSwing: [500.0, 500.0, 500.0]
  KdSwing: [12.0, 12.0, 12.0]

mpc_weights:
  Q_diag: [35.0, 35.0, 1.0, 1.0, 1.0, 250.0, 1.2, 1.2, 1.2, 22.0, 22.0, 22.0, 0.0]
  R_diag: [1.0, 1.0, 0.1, 1.0, 1.0, 0.1, 1.0, 1.0, 0.1, 1.0, 1.0, 0.1]
  R_scale: 1e-5

gait:
  gait_height: 0.12

lowlevel_cmd:
  torque_limit: [-140.0, 140.0]
  sim_stance_gain:
    hip: {mode: 10, Kp: 250.0, Kd: 12.0}
    thigh: {mode: 10, Kp: 250.0, Kd: 12.0}
    calf: {mode: 10, Kp: 400.0, Kd: 20.0}
  real_stance_gain:
    hip: {mode: 10, Kp: 80.0, Kd: 8.0}
    thigh: {mode: 10, Kp: 60.0, Kd: 6.0}
    calf: {mode: 10, Kp: 120.0, Kd: 10.0}
  stable_gain:
    hip: {mode: 10, Kp: 1.2, Kd: 1.2}
    thigh: {mode: 10, Kp: 1.2, Kd: 1.2}
    calf: {mode: 10, Kp: 1.2, Kd: 1.2}
  swing_gain:
    hip: {mode: 10, Kp: 5.0, Kd: 3.0}
    thigh: {mode: 10, Kp: 5.0, Kd: 3.0}
    calf: {mode: 10, Kp: 5.0, Kd: 3.0}
